syntax = "proto3";

package proto.sso.rpc;
option go_package = "github.com/Unpakenman/protos/gen/go/sso/rpc";

message AddEmployeeRequest{
  //роль сотрудника
  int64 role_id = 1;
  //id специализации
  int64 specialization_id = 2;
  //first_name
  string first_name = 3;
  //last_name
  string last_name = 4;
   //middle_name
  optional string middle_name = 5;
  //birthdate сотрудника
   string birthdate = 6;
   //телефон сотрудника
  string phone = 7;
  //email сотрудника
  string email = 8;


}
message AddEmployeeResponse{
  //id записи
  int64 employee_id= 1;
}