// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: sso/package.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_sso_package_proto protoreflect.FileDescriptor

const file_sso_package_proto_rawDesc = "" +
	"\n" +
	"\x11sso/package.proto\x12\tproto.sso\x1a\x16sso/rpc/register.proto\x1a\x13sso/rpc/login.proto\x1a\x15sso/rpc/isadmin.proto2\xe1\x01\n" +
	"\x04Auth\x12K\n" +
	"\bRegister\x12\x1e.proto.sso.rpc.RegisterRequest\x1a\x1f.proto.sso.rpc.RegisterResponse\x12H\n" +
	"\aIsAdmin\x12\x1d.proto.sso.rpc.IsAdminRequest\x1a\x1e.proto.sso.rpc.IsAdminResponse\x12B\n" +
	"\x05Login\x12\x1b.proto.sso.rpc.LoginRequest\x1a\x1c.proto.sso.rpc.LoginResponseB\x03Z\x01.b\x06proto3"

var file_sso_package_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: proto.sso.rpc.RegisterRequest
	(*IsAdminRequest)(nil),   // 1: proto.sso.rpc.IsAdminRequest
	(*LoginRequest)(nil),     // 2: proto.sso.rpc.LoginRequest
	(*RegisterResponse)(nil), // 3: proto.sso.rpc.RegisterResponse
	(*IsAdminResponse)(nil),  // 4: proto.sso.rpc.IsAdminResponse
	(*LoginResponse)(nil),    // 5: proto.sso.rpc.LoginResponse
}
var file_sso_package_proto_depIdxs = []int32{
	0, // 0: proto.sso.Auth.Register:input_type -> proto.sso.rpc.RegisterRequest
	1, // 1: proto.sso.Auth.IsAdmin:input_type -> proto.sso.rpc.IsAdminRequest
	2, // 2: proto.sso.Auth.Login:input_type -> proto.sso.rpc.LoginRequest
	3, // 3: proto.sso.Auth.Register:output_type -> proto.sso.rpc.RegisterResponse
	4, // 4: proto.sso.Auth.IsAdmin:output_type -> proto.sso.rpc.IsAdminResponse
	5, // 5: proto.sso.Auth.Login:output_type -> proto.sso.rpc.LoginResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sso_package_proto_init() }
func file_sso_package_proto_init() {
	if File_sso_package_proto != nil {
		return
	}
	file_sso_rpc_register_proto_init()
	file_sso_rpc_login_proto_init()
	file_sso_rpc_isadmin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_package_proto_rawDesc), len(file_sso_package_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_package_proto_goTypes,
		DependencyIndexes: file_sso_package_proto_depIdxs,
	}.Build()
	File_sso_package_proto = out.File
	file_sso_package_proto_goTypes = nil
	file_sso_package_proto_depIdxs = nil
}
